### ISSUE TITLE
Cannot run spectrast2tsv.py

### ISSUE THREAD

**Issue by Arthfael** [msproteomicstools/msproteomicstools#83]
Hi,

I am trying to follow a DIA Umpire tutorial and currently running into issues at the stage where I should be running the spectrast2tsv.py tool. Since I have a PC, I first installed Anaconda then installed msproteomicstools from the Anaconda prompt as described on github. I then first tried the following in the windows cmd prompt:
```
spectrast2tsv.py -l 350,2000 -s b,y -x 1,2 -o 6 -n 6 -p 0.05 -d -e -w swath64_noheader.txt -k openswath -a SpecLib_lgillet_I150211_008_cent_thresh2cons_openswath.csv SpecLib_lgillet_I150211_008_cent_thresh2cons.sptxt
'spectrast2tsv.py' is not recognized as an internal or external command, operable program or batch file.
```

Does this mean I should add the path for msproteomicstools to PATH? Which folder should I add? Anyway, to get around this I then tried to use a command with a direct path to the script, extracted to my desktop from the downloadable zip file provided on github:
```
C:/Users/DCP/Desktop/msproteomicstools-master/analysis/spectral_libs/spectrast2tsv.py -l 350,2000 -s b,y -x 1,2 -o 6 -n 6 -p 0.05 -d -e -w swath64_noheader.txt -k openswath -a SpecLib_lgillet_I150211_008_cent_thresh2cons_openswath.csv SpecLib_lgillet_I150211_008_cent_thresh2cons.sptxt
Traceback (most recent call last):
  File "C:\Users\Armel\Desktop\msproteomicstools-master\analysis\spectral_libs\spectrast2tsv.py", line 49, in <module>
    from configobj import ConfigObj
ModuleNotFoundError: No module named 'configobj'
```
I have tried installing "configobj" from the Anaconda command line but is says it is already installed.

I also checked and Anaconda had not added itself to PATH, however after adding manually the correct path I still get the same error as above. Any help would be greatly appreciated.
Kind regards,

Armel

**Comment by grosenberger** [comment]
Unfortunately, I have no experience with Anaconda on Windows. However, there is a detailed protocol on building libraries and using ``spectrast2tsv.py`` on Windows: http://www.nature.com/nprot/journal/v10/n3/abs/nprot.2015.015.html

Did you follow these steps? Particularly the supplementary information contains step-by-step instructions. Depending on your setup a direct path to ``spectrast2tsv.py`` might be ``C:\Anaconda\msproteomicstools\analysis\spectral_libs\spectrast2tsv.py``.

**Comment by Arthfael** [comment]
Thank you for your help and for the tutorial.

I have reinstalled Anaconda3 (I had previously installed for the current user only, as per Anaconda's recommendations, but the tutorial says to go for all users), then msproteomicstools. The script is actually located at C:\ProgramData\Anaconda3\Scripts\spectrast2tsv.py

However, if I attempt to run it, I get a new error:
```
D:\DIA test data>C:\ProgramData\Anaconda3\Scripts\spectrast2tsv.py -l 350,2000 -s b,y -x 1,2 -o 6 -n 6 -p 0.05 -d -e -w swath64_noheader.txt -k opensw
ath -a SpecLib_lgillet_I150211_008_cent_thresh2cons_openswath.csv SpecLib_lgillet_I150211_008_cent_thresh2cons.sptxt
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\spectrast2tsv.py", line 51, in <module>
    from msproteomicstoolslib.data_structures.aminoacides     import Aminoacides
  File "C:\ProgramData\Anaconda3\lib\site-packages\msproteomicstoolslib\__init__.py", line 5, in <module>
    csv.field_size_limit(sys.maxsize)
OverflowError: Python int too large to convert to C long
```
This error seems to be related to 32bit vs 64bit issues. I have definitely installed the 64bit version of Anaconda (my PC runs windows 7 64bit). Any idea how I can fix this?

**Comment by hroest** [comment]
it seems like you are running into this issue: https://stackoverflow.com/questions/15063936/csv-error-field-larger-than-field-limit-131072

I have prepared a fix here https://github.com/msproteomicstools/msproteomicstools/pull/84 -- can you try to apply this and report back?

**Comment by Arthfael** [comment]
Thank you. I have managed to install the fix (as I nice bonus I had to learn a bit more about how GitHub works), but I now run into a slightly different error: the same command as above now results in:
```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\spectrast2tsv.py", line 51, in <module>
    from msproteomicstoolslib.data_structures.aminoacides     import Aminoacides
  File "C:\ProgramData\Anaconda3\lib\site-packages\msproteomicstoolslib\__init__.py", line 5, in <module>
    maxInt = maxsize
NameError: name 'maxsize' is not defined
```

**Comment by hroest** [comment]
@Arthfael sorry, the first fix was a bit premature :-( now it should work though, I fixed the error and merged the branch

**Comment by Arthfael** [comment]
Please forget my ignorance, I am new to Github. Which version should I
install? I am taking your message means that the new master now contains
the fix. However, if I install the latest version ("pip install
msproteomicstools") the old error is back: "OverflowError: Python int too
large to convert to C long"
If I instead install #84 the error is still: "NameError: name 'maxsize' is
not defined"
(I tried "pip install msproteomicstools:master" but this clearly isn't
valid syntax...)

**Comment by hroest** [comment]
I have just updated PyPI so now a pip install should work and install version 0.7 -- probably you will need to do `pip install -U msproteomicstoolslib` to make sure it works.  Otherwise you can also get it from github, everything after commit a68be25 should be fixed.

**Comment by Arthfael** [comment]
Dear Hannes,

Sorry for the delay in getting back to you, I had to deal with other issues
which are now solved so getting back to this. Long story short, I got it to
work but this required some playing with syntax, so will leave the solution
here in case people run into the same issues:

I first tried what you suggested for updating msproteomicstoolslib:
>C:\Users\DCP>python -m pip install -U msproteomicstoolslib
Collecting msproteomicstoolslib
  Could not find a version that satisfies the requirement
msproteomicstoolslib (from versions: )
No matching distribution found for msproteomicstoolslib

I thus tried for this instead:

>python -m pip install msproteomicstools

...
Successfully installed msproteomicstools-0.7.0 scikits.datasmooth-0.61
statsmodels-0.8.0

Then, in order for the script to work I actually (after some trial and
error) had to use the following syntax:
>python C:\ProgramData\Anaconda3\Scripts\spectrast2tsv.py -l 350,2000 -s
b,y -x 1,2 -o 6 -n 6 -p 0.05 -d -e -w swath64_noheader.txt -k openswath -a
SpecLib_lgillet_I150211_008_cent_thresh2cons_openswath.csv
SpecLib_lgillet_I150211_008_cent_thresh2cons.sptxt


Note the "python" at the beginning of the line that was missing in the
previous commands I tried. The following also works (linking directly to
the extracted package on the desktop):
>python
C:\Users\DCP\Desktop\msproteomicstools-master\analysis\spectral_libs\spectrast2tsv.py
...

So I think the original "configobj" error was a windows-specific syntax
error: I was calling directly the .py script in the command line when I
should have passed it to python. I had not realised that this was needed
since all examples seem to be written for linux-like systems where you can
apparently directly call python commands without invoking python first.

Best,

Armel
